### ISSUE TITLE
Organize GH Project Board further

### ISSUE THREAD

**Issue by stefaniebutland** [nmfs-openscapes/how-we-work#2]
Hi @stefaniebutland !

Eli has restarted the the nmfs-openscapes Project Board. Would you be able to do some further set up to match what has worked for us for Openscapes and NASA Openscapes? To start, I'm thinking about

- One project board across multiple repos (not 2 separate as in screenshot below)
- Issue grouping by "this week" or "in progress" vs upcoming
- dates
- labels

This might also mean making a "how-we-work" repo for issues that don't fit in a specific repo

Thank you!

![Image](https://github.com/user-attachments/assets/3e4e3212-eddc-4d57-a3cb-b1ce4d114d5a)

**Comment by stefaniebutland** [comment]
Created [nmfs-openscapes / Main Planning](https://github.com/orgs/nmfs-openscapes/projects/35) & [how-we-work](https://github.com/nmfs-openscapes/how-we-work) repo. Added our 'usual' labels to how-we-work.

**Comment by jules32** [comment]
Thanks Stef!

To your questions, I wonder if we make an `org-planning` tag and ask Eli how she uses `story` and `epic`. "Mentors-planning" repo may be able to sunset. Could you plan to intro this project board at the Mentors call tomorrow, and maybe suggest that/ask about `story` and `epic`? It will be nice to be able to continue building this out in the next weeks.

**Comment by stefaniebutland** [comment]
Can do! Thanks Julie

**Comment by stefaniebutland** [comment]
Oct 28 nmfs huddle with Eli and Jon, Eli says she's using Milestones now and not story and epic so much. We'll develop the project board https://github.com/orgs/nmfs-openscapes/projects/35 for tasks that involve Eli, Jon, & Openscapes team, and keep Openscapes-only issues in Openscapes MainPlanning

**Comment by stefaniebutland** [comment]
closing as completed
